### ISSUE TITLE
TypeError on code start

### ISSUE THREAD

**Issue by jens365y** [omnipresense/OPS241A_NodeInterface#1]
hey, when running this code unmodified, I get the following error.

/OPS241A_NodeInterface/server.js:116
        socketServer = socketio.listen(httpServer);
                                ^

TypeError: socketio.listen is not a function

**Comment by jimwhitfield** [comment]
socket.io API changed with version 3.0.  I added instructions on how to use the 2.0 era package.
serialport API also changed.  I went ahead and checked in the one line change to work with the more recent API
